version: 1
disable_existing_loggers: False

formatters:
  default:
    "()": structlog.stdlib.ProcessorFormatter
    processor: structlog.dev.ConsoleRenderer
  json:
    "()": structlog.stdlib.ProcessorFormatter
    processor: structlog.processors.JSONRenderer

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: /opt/pdfshift/logs/app.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

root:
  level: INFO
  handlers: [console, file]

loggers:
  uvicorn:
    level: INFO
  sqlalchemy:
    level: WARNING
